services:
	webberig_htmlutilbelt_bootstrap:
    	class:	Webberig\HtmlUtilbelt\Twig\BootstrapExtension
        tags:
            - { name: twig.extension }
	webberig_htmlutilbelt_general:
    	class:	Webberig\HtmlUtilbelt\Twig\GeneralExtension
        tags:
            - { name: twig.extension }
	webberig_htmlutilbelt_heading:
    	class:	Webberig\HtmlUtilbelt\Twig\HeadingExtension
        tags:
            - { name: twig.extension }
	webberig_htmlutilbelt_link:
    	class:	Webberig\HtmlUtilbelt\Twig\LinkExtension
        tags:
            - { name: twig.extension }